export const directions={up:[0,-1],right:[1,0],down:[0,1],left:[-1,0]};
export const levels=[
{name:'One small step',concept:'A sequence is a list of instructions in order.',start:[0,4],goal:[3,4],walls:[],hint:'Add three right arrows, then run your plan.',solution:[['right',3]]},
{name:'Around the corner',concept:'Computers follow your instructions exactly. Order matters!',start:[0,4],goal:[3,1],walls:[[0,3],[1,3],[2,3]],hint:'Go right three times before going up three times.',solution:[['right',3],['up',3]]},
{name:'Take the long way',concept:'A bug is a mistake in a program. A blocked step is a clue to fix your plan.',start:[0,2],goal:[4,2],walls:[[2,1],[2,2],[2,3]],hint:'Go up to the top row, across to column 4, then down twice.',solution:[['up',2],['right',4],['down',2]]},
{name:'Loop-de-loop',concept:'A loop repeats an instruction. Use Repeat to do more with fewer command blocks.',start:[0,4],goal:[4,0],walls:[],hint:'Set Repeat to 4, then add right. Keep Repeat at 4 and add up.',solution:[['right',4],['up',4]]},
{name:'The green corridor',concept:'Break a big problem into little steps. This is called decomposition.',start:[0,4],goal:[4,0],walls:[[0,3],[1,3],[3,1],[4,1]],hint:'Right twice, up four times, then right twice.',solution:[['right',2],['up',4],['right',2]]},
{name:'Zig, then zag',concept:'Planning first can help. Imagine the robot at the end of each command.',start:[0,4],goal:[4,0],walls:[[0,3],[2,4],[2,3],[2,1],[2,0],[4,2]],hint:'Right once, up twice, right twice, up twice, then right once.',solution:[['right',1],['up',2],['right',2],['up',2],['right',1]]},
{name:'The tiny detour',concept:'Debugging means finding and fixing a mistake. Change one thing and try again.',start:[0,0],goal:[4,4],walls:[[1,0],[1,1],[1,3],[1,4],[3,2],[3,3]],hint:'Down twice, right twice, up twice, right twice, then down four times.',solution:[['down',2],['right',2],['up',2],['right',2],['down',4]]},
{name:'You’re the navigator',concept:'There can be more than one correct program. Can you find a shorter route?',start:[2,4],goal:[2,0],walls:[[2,3],[1,1],[2,1],[3,1]],hint:'Try right twice, up four times, then left twice. Can you find the mirror-image route?',solution:[['right',2],['up',4],['left',2]]}
];
export function simulate(level,commands){let pos=[...level.start];const trace=[];for(let c=0;c<commands.length;c++){const command=commands[c];if(!directions[command.dir]||!Number.isInteger(command.repeat)||command.repeat<1||command.repeat>5)throw Error('Invalid command');for(let i=0;i<command.repeat;i++){if(trace.length>=80)return{trace,success:false,reason:'limit'};const [dx,dy]=directions[command.dir];const next=[pos[0]+dx,pos[1]+dy];if(next.some(v=>v<0||v>4)||level.walls.some(([x,y])=>x===next[0]&&y===next[1]))return{trace,success:false,reason:'blocked',command:c};pos=next;trace.push({pos:[...pos],command:c});}}return{trace,success:pos[0]===level.goal[0]&&pos[1]===level.goal[1],reason:'end'};}
