import {blockLessons,freeStarter} from '../lib/blocks/curriculum.mjs';
import {registerBlocks,toolbox,validateState} from '../lib/blocks/definitions.mjs';
import {compile,runProgram,checkTask,display,kind} from '../lib/blocks/engine.mjs';
import {toPython} from '../lib/blocks/python.mjs';
import {complete} from '../lib/progress';
const root=document.querySelector<HTMLElement>('.block-lab')!;
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const slug=root.dataset.lesson!,lesson=blockLessons.find(l=>l.slug===slug);
const initial=lesson?.starter||freeStarter,key='kids-code-blocks-v1-'+slug;
let Blockly:typeof import('blockly/core'),workspace:import('blockly/core').WorkspaceSvg;
let controller:AbortController|null=null,running=false,saving=false,saveTimer:ReturnType<typeof setTimeout>,watchdog:ReturnType<typeof setTimeout>,pending:()=>void=()=>{};
let inputDefs:{name:string,type:string,value:string|number|boolean}[]=structuredClone(lesson?.inputs||[{name:'keys',type:'number',value:3}]);
const status=$('blocks-status'),run=$<HTMLButtonElement>('blocks-run'),stop=$<HTMLButtonElement>('blocks-stop'),check=$<HTMLButtonElement>('blocks-check');
function message(text:string,type=''){status.textContent=text;status.className='block-status '+type;}
function confirmAction(title:string,description:string,action:()=>void){$('blocks-confirm-title').textContent=title;$('blocks-confirm-description').textContent=description;pending=action;$<HTMLDialogElement>('blocks-confirm').showModal();}
$('blocks-confirm-yes').addEventListener('click',()=>{$<HTMLDialogElement>('blocks-confirm').close();pending();});
function renderInputs(){const holder=$('blocks-input-fields');holder.replaceChildren();if(!inputDefs.length){const p=document.createElement('p');p.className='tiny';p.textContent='This mission uses values inside your blocks. No extra input needed.';holder.append(p);}inputDefs.forEach((item,index)=>{const row=document.createElement('div');row.className='block-input-row';const label=document.createElement('label');label.htmlFor='block-input-'+index;label.textContent=item.name+' · '+item.type;const field=item.type==='boolean'?document.createElement('select'):document.createElement('input');field.id=label.htmlFor;field.dataset.inputName=item.name;if(field instanceof HTMLSelectElement){for(const v of ['true','false']){const o=document.createElement('option');o.value=v;o.textContent=v;field.append(o);}}else{field.type=item.type==='number'?'number':'text';field.maxLength=2000;if(item.type==='number'){field.min='-1000000';field.max='1000000';field.step='any';}}field.value=String(item.value);field.addEventListener('change',persist);row.append(label,field);holder.append(row);});}
function getInputs(){const inputs=Object.create(null);inputDefs.forEach((d,i)=>{const field=$<HTMLInputElement|HTMLSelectElement>('block-input-'+i);if(d.type==='number'){if(!field.value.trim()||!Number.isFinite(Number(field.value))||Math.abs(Number(field.value))>1000000)throw Error(`Give ${d.name} a number between -1,000,000 and 1,000,000.`);inputs[d.name]=Number(field.value);}else inputs[d.name]=d.type==='boolean'?field.value==='true':field.value.slice(0,2000);});return inputs;}
function snapshot(){return {version:1,workspace:Blockly.serialization.workspaces.save(workspace),inputs:inputDefs.map((d,i)=>({...d,value:d.type==='number'?Number($<HTMLInputElement>('block-input-'+i).value):d.type==='boolean'?$<HTMLSelectElement>('block-input-'+i).value==='true':$<HTMLInputElement>('block-input-'+i).value}))};}
function persist(){if(!workspace||saving)return;try{localStorage.setItem(key,JSON.stringify(snapshot()));$('blocks-save-status').textContent='✓ Your blocks and inputs are saved on this device.';}catch{$('blocks-save-status').textContent='This browser could not save your project. Use Download project to keep it.';}}
function restore(state){saving=true;try{validateState(state);Blockly.serialization.workspaces.load(structuredClone(state),workspace);workspace.scrollCenter();}finally{saving=false;}}
function busy(value:boolean){running=value;run.disabled=value;stop.disabled=!value;if(check)check.disabled=value;for(const id of ['blocks-reset','blocks-open','blocks-undo','blocks-redo','blocks-python','blocks-to-python','blocks-fit'])($<HTMLButtonElement>(id)).disabled=value;root.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-input-name]').forEach(el=>el.disabled=value);workspace.getParentSvg().style.pointerEvents=value?'none':'';}
function paint(state){$('blocks-output').textContent=state.output.length?state.output.join('\n'):'No messages yet.';$('bit-speech').textContent=state.output.at(-1)||'Following your instructions…';const holder=$('blocks-variables');holder.replaceChildren();if(!Object.keys(state.variables).length){const p=document.createElement('p');p.className='tiny';p.textContent='No variables set yet.';holder.append(p);}for(const [name,value]of Object.entries(state.variables)){const row=document.createElement('div');row.className='variable-row';const label=document.createElement('b');label.textContent=name;const type=document.createElement('small');type.textContent=kind(value);const text=document.createElement('code');text.textContent=display(value);row.append(type,label,text);holder.append(row);}}
function failure(error){if(error?.blockId)workspace.highlightBlock(error.blockId);message(error instanceof Error?error.message:'A block needs a little attention. Check its sockets and try again.','error');}
async function execute(task=false){if(running)return;try{const program=compile(workspace);const inputs=getInputs();persist();controller=new AbortController();const signal=controller.signal;busy(true);message(task?'Checking your program with the mission’s test inputs…':'Bit is following your blocks…');watchdog=setTimeout(()=>controller?.abort(),15000);if(task&&lesson){const result=await checkTask(program,lesson,{signal});if(result.passed)complete('blocks-'+slug);message(result.message,result.passed?'success':'');}else{paint({output:[],variables:{}});await runProgram(program,{inputs,signal,onStep:async state=>{paint(state);workspace.highlightBlock(state.id);const delay=matchMedia('(prefers-reduced-motion: reduce)').matches?0:Number($<HTMLSelectElement>('blocks-speed').value);await new Promise<void>(resolve=>{if(signal.aborted){resolve();return;}const finish=()=>{clearTimeout(timer);signal.removeEventListener('abort',finish);resolve();};const timer=setTimeout(finish,delay);signal.addEventListener('abort',finish,{once:true});});}});workspace.highlightBlock(null);message('Your program finished! '+(program.loose?`${program.loose} disconnected stack(s) were ignored. Only blocks inside Run or called recipes execute.`:lesson?'Ready? Use Check my task to test the goal.':'What will you change next?'));}}catch(e){failure(e);}finally{clearTimeout(watchdog);controller=null;busy(false);}}
run.addEventListener('click',()=>execute());check?.addEventListener('click',()=>execute(true));stop.addEventListener('click',()=>controller?.abort());
$('blocks-undo').addEventListener('click',()=>workspace.undo(false));$('blocks-redo').addEventListener('click',()=>workspace.undo(true));$('blocks-fit').addEventListener('click',()=>workspace.zoomToFit());
$('blocks-reset').addEventListener('click',()=>confirmAction('Back to the starting blocks?','This replaces this canvas with its starter program. Download first if you want to keep your work.',()=>{restore(initial);workspace.clearUndo();paint({output:[],variables:{}});persist();message('Fresh start. Try one small change!');}));
$('blocks-save').addEventListener('click',()=>{try{const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='kids-code-'+slug+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){failure(e);}});
$<HTMLInputElement>('blocks-open').addEventListener('change',async event=>{const field=event.target as HTMLInputElement,file=field.files?.[0];field.value='';if(!file)return;try{if(file.size>250000)throw Error('Choose a Kids Code project smaller than 250 KB.');const data=JSON.parse(await file.text());if(data.version!==1)throw Error('Choose a Kids Code Block Lab project file.');validateState(data.workspace);const importedInputs=data.inputs;if(importedInputs!==undefined&&(!Array.isArray(importedInputs)||importedInputs.length>10||importedInputs.some(d=>!d||typeof d.name!=='string'||!d.name.trim()||d.name.length>30||!['number','text','boolean'].includes(d.type)||(d.type==='number'&&(!Number.isFinite(d.value)||Math.abs(d.value)>1000000))||(d.type==='text'&&(typeof d.value!=='string'||d.value.length>2000))||(d.type==='boolean'&&typeof d.value!=='boolean'))||new Set(importedInputs.map(d=>d.name)).size!==importedInputs.length))throw Error('The project has invalid inputs.');confirmAction('Open this block project?','This replaces the current canvas. Imported projects never run automatically.',()=>{const previous=Blockly.serialization.workspaces.save(workspace);try{restore(data.workspace);if(!lesson&&importedInputs){inputDefs=importedInputs;renderInputs();}workspace.clearUndo();persist();message('Project opened. Look through the blocks, then run when you’re ready.');}catch(e){restore(previous);failure(e);}});}catch(e){failure(e);}});
$('add-block-input')?.addEventListener('click',()=>{if(running)return;const name=$<HTMLInputElement>('new-input-name').value.trim(),type=$<HTMLSelectElement>('new-input-type').value;if(!name||inputDefs.some(d=>d.name===name)){message('Give each input a different, non-empty name.');return;}if(inputDefs.length>=10){message('Ten inputs is plenty for this playground. Try reusing one.');return;}try{const values=getInputs();inputDefs=inputDefs.map(d=>({...d,value:values[d.name]}));}catch(e){failure(e);return;}inputDefs.push({name,type,value:type==='number'?0:type==='boolean'?false:''});renderInputs();persist();$<HTMLInputElement>('new-input-name').value='';});
function python(){const code=toPython(compile(workspace),getInputs());$('blocks-python-code').textContent=code;return code;}
$('blocks-python').addEventListener('click',()=>{try{python();}catch(e){failure(e);}});
$('blocks-to-python').addEventListener('click',()=>{try{const code=python();confirmAction('Try your blocks as Python?','This opens the Python playground and replaces its saved draft. Your block project stays saved here. Download your old Python draft first if you want to keep it.',()=>{try{localStorage.setItem('kids-code-draft-playground',JSON.stringify({code,input:''}));location.assign('/playground/');}catch{message('Couldn’t transfer the draft. Copy the Python code shown above into the Python playground.','error');}});}catch(e){failure(e);}});
window.addEventListener('pagehide',()=>{controller?.abort();clearTimeout(saveTimer);persist();});
async function init(){try{const core:any=await import('blockly/core');Blockly=core.default||core;const locale:any=await import('blockly/msg/en');Blockly.setLocale(locale.default||locale);registerBlocks(Blockly);$('blockly-workspace').replaceChildren();workspace=Blockly.inject('blockly-workspace',{toolbox:toolbox(lesson?.allowed),renderer:'geras',horizontalLayout:innerWidth<760,toolboxPosition:'start',media:'/blockly-media/',sounds:false,trashcan:true,maxBlocks:250,scrollbars:true,move:{scrollbars:true,drag:true,wheel:true},zoom:{controls:true,wheel:true,startScale:innerWidth<600?.75:.9,maxScale:1.4,minScale:.45,scaleSpeed:1.1},grid:{spacing:24,length:2,colour:'#d1ddc1',snap:false}});let saved;try{const raw=localStorage.getItem(key);if(raw&&raw.length<250000)saved=JSON.parse(raw);}catch{}let recovered=false;if(saved?.version===1){try{restore(saved.workspace);if(Array.isArray(saved.inputs)&&saved.inputs.length<=10){if(lesson)inputDefs=inputDefs.map(d=>{const prior=saved.inputs.find(x=>x.name===d.name&&x.type===d.type);return prior&&typeof prior.value===typeof d.value?{...d,value:prior.value}:d;});else inputDefs=saved.inputs.filter(d=>d&&typeof d.name==='string'&&d.name.length<=30&&['number','text','boolean'].includes(d.type)&&['string','number','boolean'].includes(typeof d.value));}recovered=true;}catch{restore(initial);}}else restore(initial);renderInputs();workspace.clearUndo();workspace.addChangeListener(event=>{if(event.isUiEvent||saving)return;clearTimeout(saveTimer);saveTimer=setTimeout(persist,400);$('blocks-python-code').textContent='';});new ResizeObserver(()=>Blockly.svgResize(workspace)).observe($('blockly-workspace'));for(const id of ['blocks-run','blocks-check','blocks-undo','blocks-redo','blocks-fit','blocks-reset','blocks-save','blocks-open','blocks-python','blocks-to-python']){const el=$<HTMLButtonElement>(id);if(el)el.disabled=false;}message(recovered?'Welcome back! Your saved blocks are ready.':'Your blocks are ready. Try changing a value, then press Run.');}catch(e){message('The block editor couldn’t load. Refresh the page to try again. Your lessons and saved projects are still here.','error');console.error(e);}}
init();
