import {read,save,complete} from '../lib/progress';
const colors=['#fffef9','#183e35','#086858','#b9ef79','#ffcf58','#f48059','#f2a8bd','#79bbdb'];const names=['Eraser / cream','Midnight green','Forest green','Lime','Sunshine','Tangerine','Rose','Sky blue'];
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;const grid=$('pixel-grid');let pixels=Array(144).fill(0),selected=2,history:number[][]=[];
try{const p=JSON.parse(read('pixels')||'null');if(Array.isArray(p)&&p.length===144&&p.every(n=>Number.isInteger(n)&&n>=0&&n<colors.length))pixels=p;}catch{}
function render(){grid.querySelectorAll<HTMLButtonElement>('button').forEach((b,i)=>{b.style.backgroundColor=colors[pixels[i]];b.setAttribute('aria-label',`Column ${i%12}, row ${Math.floor(i/12)}: ${names[pixels[i]]}`);});$('pixel-data').textContent=Array.from({length:12},(_,y)=>pixels.slice(y*12,y*12+12).join(' ')).join('\n');save('pixels',JSON.stringify(pixels));$<HTMLButtonElement>('pixel-undo').disabled=!history.length;if(pixels.filter(n=>n!==0).length>=6){complete('pixel-maker');$('pixel-feedback').textContent='✦ Pixel Maker discovery collected. Keep going—you’re making something yours!';}}
function remember(){history.push([...pixels]);if(history.length>30)history.shift();}
function paint(i:number){remember();pixels[i]=selected;if($<HTMLInputElement>('pixel-mirror').checked)pixels[Math.floor(i/12)*12+(11-i%12)]=selected;$('pixel-position').textContent=`Painted column ${i%12}, row ${Math.floor(i/12)} with ${names[selected].toLowerCase()}.`;render();}
for(let i=0;i<144;i++){const b=document.createElement('button');b.className='pixel-cell';b.tabIndex=i===0?0:-1;b.addEventListener('click',()=>{grid.querySelectorAll('button').forEach(el=>el.tabIndex=-1);b.tabIndex=0;paint(i);});b.addEventListener('keydown',e=>{const delta={ArrowRight:1,ArrowLeft:-1,ArrowUp:-12,ArrowDown:12}[e.key];if(delta===undefined)return;e.preventDefault();const next=i+delta;if(next<0||next>=144||(e.key==='ArrowRight'&&i%12===11)||(e.key==='ArrowLeft'&&i%12===0))return;b.tabIndex=-1;const target=grid.children[next] as HTMLButtonElement;target.tabIndex=0;target.focus();});grid.append(b);}
colors.forEach((color,i)=>{const b=document.createElement('button');b.className='swatch';b.style.backgroundColor=color;b.setAttribute('aria-label',names[i]);b.setAttribute('aria-pressed',String(i===selected));b.addEventListener('click',()=>{selected=i;$('palette').querySelectorAll('button').forEach((el,j)=>el.setAttribute('aria-pressed',String(i===j)));});$('palette').append(b);});
$('pixel-plot').addEventListener('click',()=>{const x=Number($<HTMLInputElement>('pixel-x').value),y=Number($<HTMLInputElement>('pixel-y').value);if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||x>11||y<0||y>11){$('pixel-feedback').textContent='Use whole numbers from 0 to 11 for both coordinates.';return;}paint(y*12+x);});$('pixel-undo').addEventListener('click',()=>{if(history.length){pixels=history.pop()!;render();}});$('pixel-clear').addEventListener('click',()=>{remember();pixels.fill(0);render();$('pixel-feedback').textContent='Fresh canvas! You can Undo to bring your picture back.';});
$('pixel-download').addEventListener('click',()=>{const rects=pixels.map((c,i)=>`<rect x="${i%12}" y="${Math.floor(i/12)}" width="1" height="1" fill="${colors[c]}"/>`).join('');const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12" width="600" height="600" shape-rendering="crispEdges"><title>My Kids Code pixel art</title>${rects}</svg>`;const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download='my-pixel-art.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('pixel-feedback').textContent='Your pixel art download is ready. Open the SVG image in any browser.';});render();
