import {save,read,complete} from '../lib/progress';import {projects,normalizeOutput} from '../lib/lessons.mjs';
const root=document.querySelector<HTMLElement>('.python-editor')!;const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const editor=$<HTMLTextAreaElement>('python-code'),input=$<HTMLTextAreaElement>('python-input'),output=$('python-output'),status=$('python-status'),run=$<HTMLButtonElement>('python-run'),stop=$<HTMLButtonElement>('python-stop');
let starter=root.dataset.code||'',initialInput=root.dataset.input||'',key=root.dataset.storage||'playground';let worker:Worker|null=null,timer:ReturnType<typeof setTimeout>|undefined,active=0,busy=false;
if(root.dataset.playground==='yes'){const p=projects.find(p=>p.id===new URLSearchParams(location.search).get('project'));if(p){starter=p.code;initialInput=p.input||'';key='project-'+p.id;const heading=document.getElementById('project-title');if(heading)heading.textContent=p.title;const description=document.getElementById('project-description');if(description)description.textContent=p.description;}}
try{const draft=JSON.parse(read('draft-'+key)||'null');if(draft&&typeof draft.code==='string'&&draft.code.length<=50000){editor.value=draft.code;input.value=typeof draft.input==='string'?draft.input.slice(0,10000):initialInput;}else{editor.value=starter;input.value=initialInput;}}catch{editor.value=starter;input.value=initialInput;}
if(input.value)root.querySelector('details')!.open=true;
function lines(){const n=editor.value.split('\n').length;$('line-numbers').textContent=Array.from({length:n},(_,i)=>String(i+1)).join('\n');$('line-numbers').scrollTop=editor.scrollTop;}
function store(){save('draft-'+key,JSON.stringify({code:editor.value,input:input.value}));lines();}
editor.addEventListener('input',store);input.addEventListener('input',store);editor.addEventListener('scroll',()=>{$('line-numbers').scrollTop=editor.scrollTop;});
function setBusy(value:boolean){busy=value;run.disabled=value;stop.disabled=!value;editor.readOnly=value;input.readOnly=value;$<HTMLButtonElement>('python-reset').disabled=value;$<HTMLButtonElement>('insert-indent').disabled=value;}
function terminate(message:string){active++;worker?.terminate();worker=null;clearTimeout(timer);setBusy(false);status.textContent=message;}
function friendly(error:string){if(error.includes('SyntaxError'))return 'A syntax clue: check matching quotes, parentheses, and colons.';if(error.includes('IndentationError')||error.includes('TabError'))return 'An indentation clue: use four spaces for code inside an if, loop, or function.';if(error.includes('NameError'))return 'A name clue: check spelling, and create a variable before using it.';if(error.includes('EOFError'))return 'Your program needs another answer. Open Program input and add one answer per input() call.';if(error.includes('ValueError'))return 'A value clue: int() needs a whole number, such as 7. Check your Program input.';if(error.includes('ModuleNotFoundError'))return 'That module is not available here. Try a Python standard-library module such as random or math.';if(error.includes('IndexError'))return 'A list clue: indexes start at 0. Check that the item you requested exists.';if(error.includes('Output limit'))return 'That’s a lot of output! Try fewer repeats or fewer print() calls.';return 'A clue to investigate! Read the last line of the error, adjust your code, and try again.';}
async function execute(){if(busy)return;if(!editor.value.trim()){status.textContent='Add a little code first. Try print("Hello!").';return;}if(editor.value.length>50000){status.textContent='Your program is too big for this little playground. Please keep it under 50,000 characters.';return;}store();const id=++active;setBusy(true);output.textContent='';output.classList.remove('has-error');status.textContent='Loading Python… The first visit downloads the engine. Keep this tab open.';
try{if(!worker)worker=new Worker('/python-worker.mjs',{type:'module'});clearTimeout(timer);timer=setTimeout(()=>terminate('Python took too long to load. Check your connection and press Run to retry.'),90000);
worker.onmessage=({data})=>{if(data.id!==active)return;if(data.type==='ready'){clearTimeout(timer);status.textContent='Running your program…';timer=setTimeout(()=>terminate('Stopped after 10 seconds. Your code is still here. Check for a loop that never ends, then run again.'),10000);return;}clearTimeout(timer);setBusy(false);output.textContent=data.output||'';if(data.type==='error'){output.textContent+=(data.output?'\n':'')+String(data.error);output.classList.add('has-error');status.textContent=data.stage==='load'?'Python couldn’t load. Check your internet connection, then press Run to retry. Your code is still here.':friendly(String(data.error));worker?.terminate();worker=null;return;}if(!data.output)output.textContent='Program finished with no printed output. Use print() to show something here.';const expected=root.dataset.expected;if(expected){if(normalizeOutput(data.output)===normalizeOutput(expected)){complete('python-'+root.dataset.lesson);status.textContent='✦ Goal matched! Discovery collected. Try a new idea, or head to the next lesson.';}else status.textContent='Your program ran! Compare the output with the goal above, then change one thing and try again.';}else status.textContent='Your program ran. What will you change next?';};worker.onerror=()=>{terminate('Python couldn’t start. Check your connection and try Run again. Your code is still here.');};worker.postMessage({id,code:editor.value,input:input.value});}catch{terminate('This browser could not start Python. Try a current version of Chrome, Firefox, Safari, or Edge.');}}
run.addEventListener('click',execute);stop.addEventListener('click',()=>terminate('Stopped. Your code is safe here. Edit it, then press Run to start again.'));editor.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();execute();}});
$('insert-indent').addEventListener('click',()=>{editor.setRangeText('    ',editor.selectionStart,editor.selectionEnd,'end');editor.focus();store();});$('python-reset').addEventListener('click',()=>$<HTMLDialogElement>('editor-reset-dialog').showModal());$('confirm-code-reset').addEventListener('click',()=>{editor.value=starter;input.value=initialInput;store();output.textContent='Fresh start. What will you try?';status.textContent='Starting code restored.';$<HTMLDialogElement>('editor-reset-dialog').close();});
$('python-download').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([editor.value],{type:'text/x-python'}));const a=document.createElement('a');a.href=url;a.download='my_adventure.py';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
window.addEventListener('pagehide',()=>terminate('Paused.'));lines();
