import {levels,simulate} from '../lib/robot.mjs';import {complete,readProgress} from '../lib/progress';
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const select=$<HTMLSelectElement>('mission'),repeat=$<HTMLSelectElement>('repeat'),grid=$('robot-grid'),list=$('command-list'),feedback=$('robot-feedback'),run=$<HTMLButtonElement>('robot-run'),next=$<HTMLButtonElement>('robot-next');
let levelIndex=0,commands:{dir:string,repeat:number}[]=[],running=false,generation=0;
const arrows={up:'↑',right:'→',down:'↓',left:'←'};
function options(){select.replaceChildren(...levels.map((l,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=`${i+1}. ${l.name}${readProgress().includes('robot-'+i)?' ✓':''}`;return o;}));select.value=String(levelIndex);}
function board(pos:number[],visited:number[][]=[]){const l=levels[levelIndex];grid.replaceChildren();for(let y=0;y<5;y++)for(let x=0;x<5;x++){const el=document.createElement('div');const wall=l.walls.some(([a,b])=>a===x&&b===y),current=pos[0]===x&&pos[1]===y;el.className='robot-cell'+(wall?' wall':'')+(visited.some(([a,b])=>a===x&&b===y)?' visited':'')+(current?' current':'');el.textContent=current?'🤖':l.goal[0]===x&&l.goal[1]===y?'⭐':wall?'':l.start[0]===x&&l.start[1]===y?'·':'';grid.append(el);}grid.setAttribute('aria-label',`5 by 5 board. Bit is at column ${pos[0]+1}, row ${pos[1]+1}. Star is at column ${l.goal[0]+1}, row ${l.goal[1]+1}. Obstacles: ${l.walls.map(([x,y])=>`column ${x+1} row ${y+1}`).join('; ')||'none'}. Rows count from the top.`);}
function message(text:string,kind=''){feedback.textContent=text;feedback.className='feedback '+kind;}
function drawCommands(active=-1){list.replaceChildren();if(!commands.length){const p=document.createElement('p');p.className='tiny';p.textContent='Your brilliant plan goes here. Add an arrow above!';list.append(p);}commands.forEach((c,i)=>{const b=document.createElement('button');b.className='command-chip'+(i===active?' active':'');b.textContent=`${arrows[c.dir]} ${c.dir} ×${c.repeat}  ×`;b.setAttribute('aria-label',`Remove command ${i+1}: ${c.dir} ${c.repeat} times`);b.disabled=running;b.addEventListener('click',()=>{commands.splice(i,1);drawCommands();next.hidden=true;});list.append(b);});$('command-count').textContent=`${commands.reduce((a,c)=>a+c.repeat,0)} steps planned · maximum 80`;}
function busy(value:boolean){running=value;run.disabled=value;select.disabled=value;repeat.disabled=value;document.querySelectorAll<HTMLButtonElement>('[data-dir]').forEach(b=>b.disabled=value);drawCommands();}
function reset(){generation++;busy(false);commands=[];board(levels[levelIndex].start);drawCommands();$('mission-concept').textContent=levels[levelIndex].concept;$('robot-hint-text').textContent='';next.hidden=true;message('Where should Bit go? Add commands, then run your plan.');}
select.addEventListener('change',()=>{levelIndex=Number(select.value);reset();});document.querySelectorAll<HTMLButtonElement>('[data-dir]').forEach(b=>b.addEventListener('click',()=>{const n=Number(repeat.value);if(commands.reduce((a,c)=>a+c.repeat,0)+n>80){message('That’s 80 steps! Remove a command to make room.');return;}commands.push({dir:b.dataset.dir!,repeat:n});next.hidden=true;drawCommands();}));
run.addEventListener('click',async()=>{if(!commands.length){message('Add at least one arrow first. You’re the navigator!');return;}const token=++generation;busy(true);next.hidden=true;const result=simulate(levels[levelIndex],commands);const visited:number[][]=[];board(levels[levelIndex].start);message('Bit is following your plan…');for(const step of result.trace){await new Promise(r=>setTimeout(r,window.matchMedia('(prefers-reduced-motion: reduce)').matches?40:320));if(token!==generation)return;visited.push(step.pos);board(step.pos,visited);drawCommands(step.command);}if(token!==generation)return;busy(false);if(result.success){complete('robot-'+levelIndex);options();message('⭐ You did it! Your instructions brought Bit to the star. Discovery collected!','success');next.hidden=levelIndex===levels.length-1;if(levelIndex===levels.length-1)message('⭐ All the way to the final star! Try a different route, or explore the Python trail.','success');}else if(result.reason==='blocked'){drawCommands(result.command);message(`Aha, a clue! Command ${result.command+1} runs into an obstacle or the edge. Change the plan and try again.`,'error');}else{message('Your plan ran out before Bit finished on the star. Add or change a few steps.','error');}});
$('robot-clear').addEventListener('click',reset);$('robot-hint').addEventListener('click',()=>{$('robot-hint-text').textContent=levels[levelIndex].hint;});next.addEventListener('click',()=>{levelIndex=Math.min(levelIndex+1,levels.length-1);select.value=String(levelIndex);reset();});window.addEventListener('pagehide',()=>{generation++;});options();reset();
