import test from 'node:test';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
import Blockly from 'blockly/core';import * as English from 'blockly/msg/en';
import {registerBlocks,validateState} from '../src/lib/blocks/definitions.mjs';
import {blockLessons,workspace,n,t,b,nothing,get,set,say,math,repeat,whileDo,compare,list,at,append,record,lookup,update,define,call} from '../src/lib/blocks/curriculum.mjs';
import {compile,runProgram,checkTask} from '../src/lib/blocks/engine.mjs';import {toPython} from '../src/lib/blocks/python.mjs';
Blockly.setLocale(English);registerBlocks(Blockly);
function program(state){validateState(state);const w=new Blockly.Workspace();try{Blockly.serialization.workspaces.load(state,w);return compile(w);}finally{w.dispose();}}
for(const lesson of blockLessons){
 test(`Block mission ${lesson.slug}: solution passes every scenario and starter needs a fix`,async()=>{const solution=program(lesson.solution);assert.equal((await checkTask(solution,lesson)).passed,true);let passed=false;try{passed=(await checkTask(program(lesson.starter),lesson)).passed;}catch(error){assert.ok(error.message.length);}assert.equal(passed,false,'The starter must leave a task to solve.');});
 test(`Block mission ${lesson.slug}: save/reload and exported Python preserve behavior`,async()=>{const first=new Blockly.Workspace(),second=new Blockly.Workspace();try{Blockly.serialization.workspaces.load(lesson.solution,first);const state=JSON.parse(JSON.stringify(Blockly.serialization.workspaces.save(first)));validateState(state);Blockly.serialization.workspaces.load(state,second);const p=compile(second);assert.equal((await checkTask(p,lesson)).passed,true);for(const scenario of lesson.tests){const python=spawnSync('python3',['-c',toPython(p,scenario.inputs)],{encoding:'utf8',timeout:3000});assert.equal(python.status,0,python.stderr);assert.deepEqual(python.stdout.trimEnd().split('\n'),scenario.output);}}finally{first.dispose();second.dispose();}});
}
test('Checks reject a hardcoded answer across different inputs',async()=>{const lesson=blockLessons.find(l=>l.slug==='comparisons');const p=program(workspace([say(compare(n(3),'>=',n(3)))]));assert.equal((await checkTask(p,lesson)).passed,false);});
test('Nested loop task requires actual nested loops',async()=>{const l=blockLessons.find(l=>l.slug==='nested-loops');assert.equal((await checkTask(program(workspace([repeat(n(6),[say(t('Star!'))])])),l)).passed,false);});
test('Compiler explains empty sockets, missing starts, and extra starts',()=>{assert.throws(()=>program({blocks:{blocks:[]}}),/exactly one/);const state=workspace([say(t('x'))]);state.blocks.blocks.push(structuredClone(state.blocks.blocks[0]));assert.throws(()=>program(state),/exactly one/);const missing=workspace([{type:'kc_say'}]);assert.throws(()=>program(missing),/empty socket/);});
test('Primitive types do not silently coerce text to numbers',async()=>{await assert.rejects(runProgram(program(workspace([say(math(get('x'),'+',n(1)))]))),/before using/);await assert.rejects(runProgram(program(workspace([set('x',t('5')),say(math(get('x'),'+',n(1)))]))),/needs a number/);await assert.rejects(runProgram(program(workspace([say(math(n(1),'/',n(0)))]))),/zero/);});
test('Lists enforce indexes, empty handling, and no cyclic collections',async()=>{await assert.rejects(runProgram(program(workspace([say(at(n(3),list(n(1),n(2),n(3))))]))),/index/);await assert.rejects(runProgram(program(workspace([set('x',list(n(1),n(2),n(3))),append(get('x'),get('x'))]))),/itself/);});
test('Records can safely store special keys, and unknown keys give a useful error',async()=>{const r=await runProgram(program(workspace([set('__proto__',record('__proto__',t('safe'),'energy',n(1))),say(lookup('__proto__',get('__proto__')))])));assert.deepEqual(r.output,['safe']);await assert.rejects(runProgram(program(workspace([say(lookup('missing',record('name',t('Bit'),'energy',n(1))))]))),/no key/);});
test('Loops, recursion, excessive output, and collection growth are bounded',async()=>{await assert.rejects(runProgram(program(workspace([whileDo(b(true),[set('x',n(1))])])),{maxSteps:80}),/steps/);await assert.rejects(runProgram(program(workspace([call('again')],[define('again',[call('again')])]))),/calling itself/);await assert.rejects(runProgram(program(workspace([repeat(n(110),[say(t('x'))])]))),/100 messages/);await assert.rejects(runProgram(program(workspace([set('x',list(n(1),n(2),n(3))),repeat(n(20),[set('x',list(get('x'),get('x'),get('x')))])]))),/too big/);});
test('Stop aborts a running program after a visible step',async()=>{const controller=new AbortController();let seen=0;await assert.rejects(runProgram(program(workspace([repeat(n(10),[say(t('x'))])])),{signal:controller.signal,onStep:()=>{seen++;controller.abort();}}),/Stopped/);assert.equal(seen,1);});
test('A disconnected stack never executes',async()=>{const state=workspace([say(t('connected'))]);state.blocks.blocks.push(say(t('loose')));const p=program(state),r=await runProgram(p);assert.equal(p.loose,1);assert.deepEqual(r.output,['connected']);});
test('Imports reject unknown or excessive blocks',()=>{assert.throws(()=>validateState({blocks:{blocks:[{type:'javascript_eval'}]}}),/unsupported/);assert.throws(()=>validateState({blocks:{blocks:Array.from({length:251},()=>({type:'kc_number'}))}}),/too large/);});
