// Small builders keep the curriculum readable; these produce native Blockly JSON.
const block=(op,fields={},inputs={})=>({type:'kc_'+op,fields,inputs:Object.fromEntries(Object.entries(inputs).map(([k,b])=>[k,{block:b}]))});
export const n=v=>block('number',{VALUE:v}),t=v=>block('text',{VALUE:v}),b=v=>block('boolean',{VALUE:String(v)}),nothing=()=>block('nothing');
export const get=name=>block('get',{NAME:name}),input=name=>block('input',{NAME:name});
export const say=v=>block('say',{}, {VALUE:v}),set=(name,v)=>block('set',{NAME:name},{VALUE:v});
export const math=(a,op,c)=>block('math',{OP:op},{A:a,B:c}),compare=(a,op,c)=>block('compare',{OP:op},{A:a,B:c});
export const join=(a,c)=>block('join',{}, {A:a,B:c}),kind=v=>block('kind',{}, {VALUE:v});
export function chain(items){const copies=structuredClone(items);for(let i=0;i<copies.length-1;i++)copies[i].next={block:copies[i+1]};return copies[0];}
function withBodies(op,fields,inputs,bodies){const x=block(op,fields,inputs);for(const [key,items]of Object.entries(bodies))if(items.length)x.inputs[key]={block:chain(items)};return x;}
export const iff=(test,yes,no=[])=>withBodies('if',{}, {TEST:test},{THEN:yes,ELSE:no});
export const repeat=(count,items)=>withBodies('repeat',{}, {COUNT:count},{DO:items});
export const whileDo=(test,items)=>withBodies('while',{}, {TEST:test},{DO:items});
export const each=(name,list,items)=>withBodies('each',{NAME:name},{LIST:list},{DO:items});
export const list=(a,c,d)=>block('list',{}, {A:a,B:c,C:d});
export const at=(index,l)=>block('at',{}, {INDEX:index,LIST:l});
export const length=v=>block('length',{}, {VALUE:v});
export const append=(v,l)=>block('append',{}, {VALUE:v,LIST:l});
export const record=(k,a,key,c)=>block('record',{KEY1:k,KEY2:key},{A:a,B:c});
export const lookup=(key,r)=>block('lookup',{KEY:key},{RECORD:r});
export const update=(key,r,v)=>block('update',{KEY:key},{RECORD:r,VALUE:v});
export const logic=(a,op,c)=>block('logic',{OP:op},{A:a,B:c});
export const take=(end,l)=>block('take',{END:end},{LIST:l});
export const define=(name,items)=>withBodies('define',{NAME:name},{},{DO:items});
export const call=name=>block('call',{NAME:name});
export function workspace(items,recipes=[]){return{blocks:{languageVersion:0,blocks:[{...withBodies('start',{},{},{DO:items}),x:35,y:30},...recipes.map((r,i)=>({...r,x:430,y:40+i*180}))]}};}
const test=(output,inputs={},name='Main mission')=>({output,inputs,name});
const levels=[
{slug:'sequences',title:'First this. Then that.',group:'Values & variables',topic:'Sequences & output',time:5,idea:'A program is a set of instructions. A sequence is their order. Bit follows the blocks inside “when I press Run” from top to bottom.',example:'Putting on socks and then shoes works better than doing it the other way around. Computers need the same kind of clear plan.',task:'Make Bit say Ready!, then Set!, then Go! in that exact order.',hint:'Open Start & say. Snap three “Bit says” blocks inside the Run block. Put a text block in each socket.',starter:workspace([say(t('Ready!')),say(t('Go!'))]),solution:workspace([say(t('Ready!')),say(t('Set!')),say(t('Go!'))]),tests:[test(['Ready!','Set!','Go!'])],requires:['say'],python:'hello-world',takeaway:'Order matters. An algorithm is a step-by-step plan for a task.'},
{slug:'primitive-values',title:'Numbers aren’t words.',group:'Values & variables',topic:'Primitive values & types',time:7,idea:'Programs work with values. Numbers can do math. Text (also called a string) holds words. These are simple, or primitive, kinds of values; a list or record groups values together.',example:'The number 7 and the text “7” look similar, but they have different types. Whole numbers are integers; numbers with a fractional part, like 2.5, are decimals. Python calls these int and float. Our block playground groups both under number.',task:'Make Bit say the type of the number 7, then the type of the text “7”. The output should be number, then text.',hint:'Wrap each value in a “type of” block. A number block has no quote marks; a text block does.',starter:workspace([say(kind(t('7'))),say(kind(t('7')))]),solution:workspace([say(kind(n(7))),say(kind(t('7')))]),tests:[test(['number','text'])],requires:['kind','number','text'],python:'numbers',takeaway:'A value’s type changes what your program can do with it.'},
{slug:'booleans-and-nothing',title:'Yes, no, and not yet.',group:'Values & variables',topic:'Booleans & missing values',time:7,idea:'A boolean has exactly two values: true and false. Programs use them for decisions. “Nothing” means there is no value here yet. It is different from false, zero, or an empty string.',example:'has_ticket could be true or false. favorite_game might be nothing until you choose one. In Python these are True, False, and None; many other languages use null for an absent value.',task:'Print the type of true, then the type of nothing. Bit should say boolean, then nothing.',hint:'Find true and nothing in Values & math. Place each one inside a type-of block.',starter:workspace([say(kind(n(0))),say(kind(t('')))]),solution:workspace([say(kind(b(true))),say(kind(nothing()))]),tests:[test(['boolean','nothing'])],requires:['boolean','nothing','kind'],python:'conditionals',takeaway:'False is an answer. Nothing means a value is absent.'},
{slug:'variables',title:'A pocket with a name.',group:'Values & variables',topic:'Variables & assignment',time:7,idea:'A variable gives a value a name. Set the variable first, then use its name to read the value later. You can change its value without changing its name.',example:'A pocket labeled score might hold 2 now and 5 later. “Set score to 5” replaces the old value; it does not add 5 to it.',task:'Set score to 5 and make Bit say the value of score. Look at the variable watcher to see what is inside the pocket.',hint:'Change the number in the set block to 5. Keep the value-of block so your program reads the variable.',starter:workspace([set('score',n(2)),say(get('score'))]),solution:workspace([set('score',n(5)),say(get('score'))]),tests:[test(['5'])],requires:['set','get'],python:'variables',takeaway:'Assignment changes the value a name refers to. Names are case-sensitive: score and Score are different.'},
{slug:'arithmetic',title:'The snack shop.',group:'Values & variables',topic:'Arithmetic & expressions',time:8,idea:'An expression combines values to make a new value. Add, subtract, multiply, and divide with math blocks. Blocks nested inside other blocks are worked out first.',example:'For 4 friends with 3 cookies each and 2 spare cookies, work out 4 × 3 first, then add 2. That is 14 cookies.',task:'Calculate 4 × 3 + 2 using math blocks, store the result in cookies, and print cookies.',hint:'Put a multiply block inside the left socket of an add block. This is how block nesting chooses the order.',starter:workspace([set('cookies',math(n(4),'+',n(3))),say(get('cookies'))]),solution:workspace([set('cookies',math(math(n(4),'*',n(3)),'+',n(2))),say(get('cookies'))]),tests:[test(['14'])],requires:['math','set','get'],python:'numbers',takeaway:'An expression has a value. Nesting makes the order of operations visible.'},
{slug:'comparisons',title:'Ask a true-or-false question.',group:'Decisions',topic:'Comparisons',time:7,idea:'Comparisons ask questions about values. Is 5 greater than 3? Are two messages equal? Their answer is always a boolean: true or false.',example:'“Set stars to 3” changes a variable. “stars = 3” inside a comparison asks whether they are equal. In Python, = assigns and == compares.',task:'Use a comparison to print true when the keys input is at least 3, and false otherwise. We’ll check 2, 3, and 5 keys.',hint:'Use the ≥ comparison. “At least 3” includes exactly 3.',inputs:[{name:'keys',type:'number',value:3}],starter:workspace([say(compare(input('keys'),'>',n(3)))]),solution:workspace([say(compare(input('keys'),'>=',n(3)))]),tests:[test(['false'],{keys:2},'Two keys'),test(['true'],{keys:3},'Exactly three keys'),test(['true'],{keys:5},'Five keys')],requires:['compare','input'],python:'conditionals',takeaway:'Boundary values—like exactly 3—are useful tests.'},
{slug:'if-else',title:'Two doors. One decision.',group:'Decisions',topic:'If / else',time:8,idea:'An if/else block chooses which instructions to run. When its condition is true, the first branch runs. Otherwise, the else branch runs. Only one branch is chosen each time.',example:'If it is raining, bring a raincoat. Else, bring a sun hat. A condition turns one program into two possible adventures.',task:'If keys is at least 3, say Door unlocked! Otherwise say Find more keys! Your program must work for both cases.',hint:'Use the ≥ comparison inside if. Put a say block in both the then and else sections.',inputs:[{name:'keys',type:'number',value:3}],starter:workspace([iff(compare(input('keys'),'>',n(3)),[say(t('Door unlocked!'))],[say(t('Find more keys!'))])]),solution:workspace([iff(compare(input('keys'),'>=',n(3)),[say(t('Door unlocked!'))],[say(t('Find more keys!'))])]),tests:[test(['Find more keys!'],{keys:2},'Not enough keys'),test(['Door unlocked!'],{keys:3},'Exactly enough keys'),test(['Door unlocked!'],{keys:5},'Extra keys')],requires:['if','compare','input'],python:'conditionals',takeaway:'An if/else gives your program different paths for different situations.'},
{slug:'boolean-logic',title:'The secret clubhouse.',group:'Decisions',topic:'And, or & not',time:9,idea:'Combine boolean questions with and, or, and not. “And” needs both answers to be true. “Or” needs at least one. “Not” flips true to false, or false to true.',example:'A clubhouse might need a ticket AND permission. An emergency exit might open with a key OR a button. “Not raining” means the raining boolean is false.',task:'Say Come in! only if has_ticket AND has_permission are true. Otherwise say Not yet. We’ll try all four combinations.',hint:'Change the or block to and. In Inputs, try one true and one false before checking the task.',inputs:[{name:'has_ticket',type:'boolean',value:true},{name:'has_permission',type:'boolean',value:false}],starter:workspace([iff(logic(input('has_ticket'),'or',input('has_permission')),[say(t('Come in!'))],[say(t('Not yet.'))])]),solution:workspace([iff(logic(input('has_ticket'),'and',input('has_permission')),[say(t('Come in!'))],[say(t('Not yet.'))])]),tests:[test(['Come in!'],{has_ticket:true,has_permission:true},'Both true'),test(['Not yet.'],{has_ticket:true,has_permission:false},'Only ticket'),test(['Not yet.'],{has_ticket:false,has_permission:true},'Only permission'),test(['Not yet.'],{has_ticket:false,has_permission:false},'Neither')],requires:['logic','if','input'],extra:['not'],python:'conditionals',takeaway:'Boolean logic combines small questions into more useful decisions.'},
{slug:'repeat-loops',title:'Encore, little robot!',group:'Loops',topic:'Counted loops',time:7,idea:'A counted loop repeats a set of instructions a chosen number of times. You write the instructions once, then let the loop do the repetition.',example:'Repeating “clap” four times is a short way of saying clap, clap, clap, clap. A count of zero runs the inside instructions zero times.',task:'Use a repeat block to make Bit say Hooray! exactly four times.',hint:'Put one say block inside repeat and set the count to 4.',starter:workspace([repeat(n(2),[say(t('Hooray!'))])]),solution:workspace([repeat(n(4),[say(t('Hooray!'))])]),tests:[test(['Hooray!','Hooray!','Hooray!','Hooray!'])],requires:['repeat'],python:'loops',takeaway:'A loop can replace repeated instructions with one reusable pattern.'},
{slug:'while-loops',title:'Count down to lift-off.',group:'Loops',topic:'While loops & stopping',time:10,idea:'A while loop repeats as long as its condition is true. It checks before each trip around the loop. Something usually needs to change inside so the loop can eventually stop.',example:'While there are cookies left, eat one cookie. If you never reduce the cookie count, that condition never becomes false!',task:'Start count at 3. While count is greater than 0, say count and subtract 1. After the loop, say Lift-off! Output: 3, 2, 1, Lift-off!',hint:'Change count inside the loop: set count to value of count minus 1. The Lift-off message belongs after the whole loop.',starter:workspace([set('count',n(3)),whileDo(compare(get('count'),'>',n(0)),[say(get('count')),set('count',math(get('count'),'-',n(0)))]),say(t('Lift-off!'))]),solution:workspace([set('count',n(3)),whileDo(compare(get('count'),'>',n(0)),[say(get('count')),set('count',math(get('count'),'-',n(1)))]),say(t('Lift-off!'))]),tests:[test(['3','2','1','Lift-off!'])],requires:['while','set','math'],python:'loops',takeaway:'Make progress toward a false condition. Stop is always available if a loop runs away.'},
{slug:'nested-loops',title:'A pattern inside a pattern.',group:'Loops',topic:'Nested loops',time:9,idea:'A nested loop is a loop inside another loop. Each time the outer loop runs, the inner loop starts again. This is useful for grids and repeated patterns.',example:'Two rows of three chairs means the inner “three chairs” job happens twice: 2 × 3 = 6 chairs.',task:'Use two nested repeat blocks. The outside repeats 2 times, the inside 3 times, and Bit says Star! inside. Print 6 stars in total.',hint:'Place the 3-repeat loop inside the 2-repeat loop, with say inside both.',starter:workspace([repeat(n(2),[repeat(n(2),[say(t('Star!'))])])]),solution:workspace([repeat(n(2),[repeat(n(3),[say(t('Star!'))])])]),tests:[test(Array(6).fill('Star!'))],requires:['repeat'],structural:'nested-repeat',python:'loops',takeaway:'The inner work happens again for every outer step.'},
{slug:'lists',title:'A backpack full of things.',group:'Data structures',topic:'Lists & collections',time:8,idea:'A data structure organizes values. A list keeps a collection in order, and it can grow. Unlike one primitive value, a list can hold many values together.',example:'Your backpack might contain a map, a snack, and a torch. Adding a compass puts a fourth item at the end.',task:'Create a bag list containing map, snack, and torch. Add compass to the end. Print the list’s length: 4.',hint:'Use the add-to-end block with a text compass and the value of bag. Then use length of bag.',starter:workspace([set('bag',list(t('map'),t('snack'),t('torch'))),say(length(get('bag')))]),solution:workspace([set('bag',list(t('map'),t('snack'),t('torch'))),append(t('compass'),get('bag')),say(length(get('bag')))]),tests:[test(['4'])],requires:['list','append','length'],extra:['empty_list'],python:'lists',takeaway:'Lists have an order and a length. Adding an item changes the collection.'},
{slug:'list-indexes',title:'Find the creature.',group:'Data structures',topic:'Indexing & zero',time:8,idea:'An index is a position inside a list. We count from zero: index 0 is the first item, index 1 is the second, and so on.',example:'For [otter, dragon, robot], the dragon lives at index 1. A list with 3 items has indexes 0, 1, and 2; index 3 is outside it.',task:'Store otter, dragon, robot in creatures. Print the item at index 1, then the item at index 2: dragon, then robot.',hint:'Change the first index from 0 to 1. Add another say block with item at index 2.',starter:workspace([set('creatures',list(t('otter'),t('dragon'),t('robot'))),say(at(n(0),get('creatures')))]),solution:workspace([set('creatures',list(t('otter'),t('dragon'),t('robot'))),say(at(n(1),get('creatures'))),say(at(n(2),get('creatures')))]),tests:[test(['dragon','robot'])],requires:['at','list'],python:'lists',takeaway:'The last valid index is always one less than the list’s length.'},
{slug:'for-each',title:'Hello to every creature.',group:'Data structures',topic:'Iteration over a list',time:9,idea:'A for-each loop visits each item in a list, in order. On each trip, its variable holds the next item. You can use that value inside the loop.',example:'For each friend in your party, give that friend a cookie. You don’t have to know how many friends there are before you begin.',task:'Loop through otter, dragon, and robot. Say Hello, otter!, Hello, dragon!, and Hello, robot! using the item variable and join blocks.',hint:'The creature variable changes each trip. Join “Hello, ” with creature, then join “!” onto the end.',starter:workspace([set('creatures',list(t('otter'),t('dragon'),t('robot'))),each('creature',get('creatures'),[say(get('creature'))])]),solution:workspace([set('creatures',list(t('otter'),t('dragon'),t('robot'))),each('creature',get('creatures'),[say(join(join(t('Hello, '),get('creature')),t('!')))])]),tests:[test(['Hello, otter!','Hello, dragon!','Hello, robot!'])],requires:['each','join'],python:'lists',takeaway:'Iteration lets the same instructions work on every item in a collection.'},
{slug:'records',title:'Build Bit’s character card.',group:'Data structures',topic:'Records / dictionaries',time:10,idea:'A record stores named keys and values. You look up a value using its key, rather than its position. Python calls this kind of structure a dictionary.',example:'A character record can hold name: Bit and energy: 50. Looking up energy gives 50. Updating that key changes only the energy value.',task:'Create hero with name Bit and energy 50. Add 10 to its energy using an update block. Print its name, then its new energy: Bit, 60.',hint:'Inside the update block, add 10 to the lookup of energy in hero. Don’t replace the whole hero variable with a number.',starter:workspace([set('hero',record('name',t('Bit'),'energy',n(50))),say(lookup('name',get('hero'))),say(lookup('energy',get('hero')))]),solution:workspace([set('hero',record('name',t('Bit'),'energy',n(50))),update('energy',get('hero'),math(lookup('energy',get('hero')),'+',n(10))),say(lookup('name',get('hero'))),say(lookup('energy',get('hero')))]),tests:[test(['Bit','60'])],requires:['record','lookup','update'],python:'dictionaries',takeaway:'Lists use positions. Records use meaningful keys.'},
{slug:'stacks-and-queues',title:'Pancakes and waiting lines.',group:'Data structures',topic:'Stacks & queues',time:10,idea:'A stack takes the last added item first, like pancakes taken from the top. A queue takes the first added item first, like friends waiting for a slide. We can model both with a list.',example:'Add red, blue, then green. A stack gives green first. A queue gives red first. Taking an item removes it from the collection.',task:'Make a list red, blue, green. Take and print the last item, then take and print the first item, then print the remaining length. Output: green, red, 1.',hint:'Use two take blocks inside say blocks: last first, then first. The variable watcher will show the list shrinking.',starter:workspace([set('line',list(t('red'),t('blue'),t('green'))),say(take('first',get('line'))),say(length(get('line')))]),solution:workspace([set('line',list(t('red'),t('blue'),t('green'))),say(take('last',get('line'))),say(take('first',get('line'))),say(length(get('line')))]),tests:[test(['green','red','1'])],requires:['take','length'],python:'lists',takeaway:'A data structure’s rules determine which item comes out next.'},
{slug:'functions',title:'Bottle a little superpower.',group:'Build & debug',topic:'Functions & reuse',time:9,idea:'A function is a reusable set of instructions. Our recipe blocks are simple functions: define a recipe once, then call it by name when you need it.',example:'A celebrate recipe might say Yay! and We did it! Calling it twice repeats the whole recipe twice. Defining it alone doesn’t run it.',task:'Define a celebrate recipe that says Yay! then We did it! Call it twice from the Run block.',hint:'Keep the definition separate from Run. Snap two “run recipe celebrate” blocks inside Run.',starter:workspace([call('celebrate')],[define('celebrate',[say(t('Yay!')),say(t('We did it!'))])]),solution:workspace([call('celebrate'),call('celebrate')],[define('celebrate',[say(t('Yay!')),say(t('We did it!'))])]),tests:[test(['Yay!','We did it!','Yay!','We did it!'])],requires:['call'],python:'functions',takeaway:'Recipes here share the program’s variables and have no parameters. Python functions can take parameters and return values: try that next on the Python trail.'},
{slug:'inputs',title:'One program. New possibilities.',group:'Build & debug',topic:'Input, processing & output',time:8,idea:'Input is information your program receives. Processing is what it does with that information. Output is what it gives back. Different inputs can make the same program produce different results.',example:'A snack calculator takes a number of friends, multiplies by two snacks each, and prints the total. Four friends gives eight snacks; six friends gives twelve.',task:'Read friends from the input panel, multiply it by 2, and print the result. We’ll check 0, 4, and 6 friends.',hint:'Use the input friends block instead of a fixed number. Change friends in the panel and run again to test it.',inputs:[{name:'friends',type:'number',value:4}],starter:workspace([say(math(n(4),'*',n(2)))]),solution:workspace([say(math(input('friends'),'*',n(2)))]),tests:[test(['0'],{friends:0},'No friends'),test(['8'],{friends:4},'Four friends'),test(['12'],{friends:6},'Six friends')],requires:['input','math'],python:'input',takeaway:'A program is more useful when it can work with new input.'},
{slug:'debugging',title:'The case of the missing point.',group:'Build & debug',topic:'Debugging & testing',time:10,idea:'Debugging means finding why your program does something unexpected and fixing it. A useful strategy is to predict, run, look at the values, and change one thing.',example:'If three rounds should give three points but the score stays at zero, inspect what the loop changes. Is it adding zero instead of one?',task:'Fix this score counter. It starts at zero, adds one each round, and prints the final score. It must work for 1, 3, and 5 rounds.',hint:'The loop count is already correct. Look closely at the number added to score inside the loop.',inputs:[{name:'rounds',type:'number',value:3}],starter:workspace([set('score',n(0)),repeat(input('rounds'),[set('score',math(get('score'),'+',n(0)))]),say(get('score'))]),solution:workspace([set('score',n(0)),repeat(input('rounds'),[set('score',math(get('score'),'+',n(1)))]),say(get('score'))]),tests:[test(['1'],{rounds:1},'One round'),test(['3'],{rounds:3},'Three rounds'),test(['5'],{rounds:5},'Five rounds')],requires:['repeat','set','math','get'],python:'loops',takeaway:'A bug is information. Test more than one input to build confidence in a fix.'},
{slug:'treasure-machine',title:'Build a treasure machine.',group:'Build & debug',topic:'Your first complete algorithm',time:12,idea:'Now combine collections, variables, loops, and decisions. Break the task into little jobs: store the data, count matching items, and report the result.',example:'A game can visit every treasure in a bag and count the gold pieces. The same plan works even when the bag’s contents change.',task:'Start with [gold, stone, gold]. Set score to 0. Visit each item; if it equals gold, add 1 to score. After the loop, print score: 2.',hint:'Put an if block inside for each. Put the final say after the entire loop, so it prints only once.',starter:workspace([set('bag',list(t('gold'),t('stone'),t('gold'))),set('score',n(0)),each('item',get('bag'),[set('score',math(get('score'),'+',n(1)))]),say(get('score'))]),solution:workspace([set('bag',list(t('gold'),t('stone'),t('gold'))),set('score',n(0)),each('item',get('bag'),[iff(compare(get('item'),'=',t('gold')),[set('score',math(get('score'),'+',n(1)))])]),say(get('score'))]),tests:[test(['2'])],requires:['list','each','if','compare','math'],python:'mini-game',takeaway:'Big programs are small ideas working together. Change the treasure list and invent a new scoring rule.'}
];
function allTypes(state){const found=new Set(['start','say','number','text']);function walk(x){if(!x||typeof x!=='object')return;if(typeof x.type==='string'&&x.type.startsWith('kc_'))found.add(x.type.slice(3));Object.values(x).forEach(v=>{if(v&&typeof v==='object')walk(v);});}walk(state);return found;}
export const blockLessons=levels.map((l,index)=>({...l,index,inputs:l.inputs||[],allowed:[...new Set([...allTypes(l.starter),...allTypes(l.solution),...(l.extra||[])])]}));
export const freeStarter=workspace([set('score',n(0)),repeat(n(3),[set('score',math(get('score'),'+',n(1))),say(join(t('High five number '),get('score')))])]);
