export class BlockError extends Error {constructor(message,id){super(message);this.blockId=id;}}
export const kind=v=>v===null?'nothing':Array.isArray(v)?'list':typeof v==='object'?'record':({string:'text',boolean:'boolean',number:'number'})[typeof v]||'nothing';
export function display(v){if(v===null)return 'nothing';if(typeof v==='boolean')return String(v);if(typeof v==='object')return JSON.stringify(v);return String(v);}
export function compile(workspace){if(workspace.getAllBlocks(false).length>250)throw new BlockError('Keep your project under 250 blocks.');const tops=workspace.getTopBlocks(true).filter(b=>b.isEnabled());const starts=tops.filter(b=>b.type==='kc_start');if(starts.length!==1)throw new BlockError('Use exactly one “when I press Run” block.');const used=new Set();let count=0;
function node(b,depth=0){if(!b||!b.isEnabled())throw new BlockError('There’s an empty socket. Snap a value block into it.',b?.id);if(depth>50||++count>1500)throw new BlockError('This stack is too deep. Try smaller recipes.',b.id);used.add(b.id);const n={op:b.type.replace(/^kc_/,''),id:b.id,fields:{},inputs:{},bodies:{}};for(const input of b.inputList){for(const f of input.fieldRow)if(f.name)n.fields[f.name]=b.getFieldValue(f.name);if(input.connection){if(input.type===3)n.bodies[input.name]=chain(b.getInputTargetBlock(input.name),depth+1);else n.inputs[input.name]=node(b.getInputTargetBlock(input.name),depth+1);}}return n;}
function chain(b,depth=0){const out=[];while(b){if(b.isEnabled())out.push(node(b,depth));b=b.getNextBlock();}return out;}
const start=starts[0];used.add(start.id);const body=chain(start.getInputTargetBlock('DO'));const functions=Object.create(null);for(const b of tops.filter(b=>b.type==='kc_define')){const name=String(b.getFieldValue('NAME'));if(!name.trim()||Object.hasOwn(functions,name))throw new BlockError('Give each recipe its own name.',b.id);used.add(b.id);functions[name]=chain(b.getInputTargetBlock('DO'));}const loose=tops.filter(b=>!['kc_start','kc_define'].includes(b.type)).length;return {body,functions,loose,used:[...used]};}
export async function runProgram(program,{inputs={},onStep=null,signal=null,maxSteps=2000}={}){const variables=Object.create(null),output=[],executed=new Set();let steps=0,depth=0;
const fail=(msg,n)=>{throw new BlockError(msg,n?.id);};
function tick(n){if(signal?.aborted)fail('Stopped. Your blocks are still here.',n);if(++steps>maxSteps)fail('That’s a lot of steps! Check your while condition: something inside the loop must change it.',n);executed.add(n.op);}
function num(v,n){if(typeof v!=='number'||!Number.isFinite(v))fail('This socket needs a number. Text like “5” is a different type.',n);return v;}
function bool(v,n){if(typeof v!=='boolean')fail('A decision needs true or false. Try a comparison block.',n);return v;}
function list(v,n){if(!Array.isArray(v))fail('This block needs a list.',n);return v;}
function record(v,n){if(!v||Array.isArray(v)||typeof v!=='object')fail('This block needs a record of keys and values.',n);return v;}
function dataBudget(v,n){let count=0,chars=0;function visit(x,depth){if(++count>1000||depth>20)fail('This collection is getting too big. Try fewer nested items.',n);if(typeof x==='string'){chars+=x.length;if(chars>12000)fail('Try less text in this collection.',n);}if(x&&typeof x==='object')Object.values(x).forEach(y=>visit(y,depth+1));}visit(v,0);return v;}
function bounded(v,n){if(typeof v==='number'&&!Number.isFinite(v))fail('That number is too large, or a division used zero.',n);if(typeof v==='string'&&v.length>2000)fail('This message is getting long. Try shorter text.',n);return v;}
function value(n){tick(n);const f=n.fields,e=k=>value(n.inputs[k]);let a,b;switch(n.op){case'number':return num(Number(f.VALUE),n);case'text':return bounded(String(f.VALUE),n);case'boolean':return f.VALUE==='true';case'nothing':return null;case'kind':return kind(e('VALUE'));case'get':if(!Object.hasOwn(variables,f.NAME))fail(`Set the variable “${f.NAME}” before using it.`,n);return variables[f.NAME];case'input':if(!Object.hasOwn(inputs,f.NAME))fail(`Add an input named “${f.NAME}” in the input panel.`,n);return inputs[f.NAME];case'math':a=num(e('A'),n);b=num(e('B'),n);if((f.OP==='/'||f.OP==='%')&&b===0)fail('You can’t divide by zero. Try a different number.',n);return bounded(({'+':()=>a+b,'-':()=>a-b,'*':()=>a*b,'/':()=>a/b,'%':()=>a%b}[f.OP])(),n);case'join':return bounded(display(e('A'))+display(e('B')),n);case'compare':a=e('A');b=e('B');if(f.OP==='=')return typeof a===typeof b&&JSON.stringify(a)===JSON.stringify(b);if(f.OP==='!=')return !(typeof a===typeof b&&JSON.stringify(a)===JSON.stringify(b));a=num(a,n);b=num(b,n);return ({'<':()=>a<b,'<=':()=>a<=b,'>':()=>a>b,'>=':()=>a>=b}[f.OP])();case'logic':a=bool(e('A'),n);return f.OP==='and'?a&&bool(e('B'),n):a||bool(e('B'),n);case'not':return !bool(e('VALUE'),n);case'list':return dataBudget([e('A'),e('B'),e('C')],n);case'empty_list':return[];case'at':a=list(e('LIST'),n);b=num(e('INDEX'),n);if(!Number.isInteger(b)||b<0||b>=a.length)fail('That list index doesn’t exist. Start at 0 and stay below the list’s length.',n);return a[b];case'length':a=e('VALUE');if(typeof a!=='string'&&!Array.isArray(a))fail('Length works with text or a list.',n);return a.length;case'take':a=list(e('LIST'),n);if(!a.length)fail('The list is empty. Add an item before taking one.',n);return f.END==='first'?a.shift():a.pop();case'record':if(f.KEY1===f.KEY2)fail('Use a different key for each value in your record.',n);return dataBudget(Object.assign(Object.create(null),{[f.KEY1]:e('A'),[f.KEY2]:e('B')}),n);case'lookup':a=record(e('RECORD'),n);if(!Object.hasOwn(a,f.KEY))fail(`There is no key “${f.KEY}” in this record yet.`,n);return a[f.KEY];default:fail('This block cannot go inside a value socket.',n);}}
function noCycle(target,v,n){const seen=new Set();function visit(x,level){if(x===target)fail('A collection can’t contain itself in this playground.',n);if(level>30)fail('Try fewer nested collections.',n);if(x&&typeof x==='object'&&!seen.has(x)){seen.add(x);Object.values(x).forEach(y=>visit(y,level+1));}}visit(v,0);}
async function chain(body){for(const n of body){tick(n);const f=n.fields,e=k=>value(n.inputs[k]);switch(n.op){case'say':if(output.length>=100)fail('The stage is full! Keep your output to 100 messages.',n);output.push(display(e('VALUE')));break;case'set':if(!String(f.NAME).trim())fail('Give this variable a name.',n);if(!Object.hasOwn(variables,f.NAME)&&Object.keys(variables).length>=50)fail('Use fewer than 50 variables.',n);variables[f.NAME]=e('VALUE');dataBudget(variables,n);break;case'if':await chain(bool(e('TEST'),n)?n.bodies.THEN:n.bodies.ELSE);break;case'repeat':{const count=num(e('COUNT'),n);if(!Number.isInteger(count)||count<0||count>500)fail('Repeat needs a whole number from 0 to 500.',n);for(let i=0;i<count;i++){tick(n);await chain(n.bodies.DO);}break;}case'while':while(bool(e('TEST'),n)){tick(n);await chain(n.bodies.DO);if(!n.bodies.DO.length)await new Promise(r=>setTimeout(r,0));}break;case'each':{const items=[...list(e('LIST'),n)];for(const item of items){tick(n);variables[f.NAME]=item;await chain(n.bodies.DO);}break;}case'append':{const target=list(e('LIST'),n),v=e('VALUE');if(target.length>=100)fail('Keep each list under 100 items.',n);noCycle(target,v,n);dataBudget([...target,v],n);target.push(v);dataBudget(variables,n);break;}case'update':{const target=record(e('RECORD'),n),v=e('VALUE');if(Object.keys(target).length>=50&&!Object.hasOwn(target,f.KEY))fail('Keep records under 50 keys.',n);noCycle(target,v,n);dataBudget({...target,[f.KEY]:v},n);target[f.KEY]=v;dataBudget(variables,n);break;}case'call':if(!Object.hasOwn(program.functions,f.NAME))fail(`Add a “define recipe ${f.NAME}” block first.`,n);if(++depth>20)fail('This recipe keeps calling itself. Try a recipe that finishes.',n);await chain(program.functions[f.NAME]);depth--;break;default:fail('Use an instruction block inside your program.',n);}if(onStep)await onStep({id:n.id,variables,output,steps});else if(steps%40===0)await new Promise(r=>setTimeout(r,0));if(signal?.aborted)fail('Stopped. Your blocks are still here.',n);}}
await chain(program.body);return {variables,output,steps,executed:[...executed]};}
export async function checkTask(program,lesson,options={}){if(!program.body.length)return{passed:false,message:'Connect some instructions inside “when I press Run” first.'};if(lesson.structural==='nested-repeat'){const nested=(body,inside=false)=>body.some(n=>(n.op==='repeat'&&inside)||Object.values(n.bodies).some(nodes=>nested(nodes,inside||n.op==='repeat')));if(!nested(program.body))return{passed:false,message:'Put one repeat block inside another repeat block for this pattern.'};}for(const scenario of lesson.tests){const result=await runProgram(program,{inputs:scenario.inputs,...options});const missing=(lesson.requires||[]).filter(op=>!result.executed.includes(op));if(missing.length)return{passed:false,message:`Use the ${missing.join(', ')} block${missing.length>1?'s':''} to practice this lesson’s idea.`};if(JSON.stringify(result.output)!==JSON.stringify(scenario.output))return{passed:false,message:`Try “${scenario.name}”: expected ${scenario.output.map(x=>JSON.stringify(x)).join(', ')}, but got ${result.output.map(x=>JSON.stringify(x)).join(', ')||'no messages'}.`,scenario};}return{passed:true,message:`✦ You did it! ${lesson.tests.length===1?'The task check passed.':`All ${lesson.tests.length} task checks passed.`} Discovery collected.`};}
