// Export an understandable Python version. Only block fields become quoted data.
export function toPython(program,inputs={}){
const quote=v=>JSON.stringify(String(v));
const literal=v=>v===null?'None':typeof v==='boolean'?(v?'True':'False'):typeof v==='number'?String(v):Array.isArray(v)?'['+v.map(literal).join(', ')+']':typeof v==='object'?'{'+Object.entries(v).map(([k,x])=>quote(k)+': '+literal(x)).join(', ')+'}':quote(v);
const functions=new Map(Object.keys(program.functions).map((name,i)=>[name,'recipe_'+(i+1)]));
const e=n=>{const f=n.fields,v=k=>e(n.inputs[k]);switch(n.op){case'number':return String(Number(f.VALUE));case'text':return quote(f.VALUE);case'boolean':return f.VALUE==='true'?'True':'False';case'nothing':return'None';case'get':return'variables['+quote(f.NAME)+']';case'input':return'inputs['+quote(f.NAME)+']';case'kind':return'value_type('+v('VALUE')+')';case'math':return f.OP==='%'?'math.fmod('+v('A')+', '+v('B')+')':'('+v('A')+' '+f.OP+' '+v('B')+')';case'compare':return '('+v('A')+' '+(f.OP==='='?'==':f.OP)+' '+v('B')+')';case'logic':return '('+v('A')+' '+f.OP+' '+v('B')+')';case'not':return'(not '+v('VALUE')+')';case'join':return'(show('+v('A')+') + show('+v('B')+'))';case'list':return'['+v('A')+', '+v('B')+', '+v('C')+']';case'empty_list':return'[]';case'at':return v('LIST')+'[int('+v('INDEX')+')]';case'length':return'len('+v('VALUE')+')';case'take':return v('LIST')+'.pop('+(f.END==='first'?'0':'')+')';case'record':return'{'+quote(f.KEY1)+': '+v('A')+', '+quote(f.KEY2)+': '+v('B')+'}';case'lookup':return v('RECORD')+'['+quote(f.KEY)+']';default:throw Error('Unsupported value block.');}};
const lines=(body,depth=0)=>{const pad='    '.repeat(depth);if(!body.length)return pad+'pass\n';return body.map(n=>{const f=n.fields,v=k=>e(n.inputs[k]);switch(n.op){case'say':return pad+'print(show('+v('VALUE')+'))\n';case'set':return pad+'variables['+quote(f.NAME)+'] = '+v('VALUE')+'\n';case'if':return pad+'if '+v('TEST')+':\n'+lines(n.bodies.THEN,depth+1)+(n.bodies.ELSE.length?pad+'else:\n'+lines(n.bodies.ELSE,depth+1):'');case'repeat':return pad+'for _ in range(int('+v('COUNT')+')):\n'+lines(n.bodies.DO,depth+1);case'while':return pad+'while '+v('TEST')+':\n'+lines(n.bodies.DO,depth+1);case'each':return pad+'for variables['+quote(f.NAME)+'] in list('+v('LIST')+'):\n'+lines(n.bodies.DO,depth+1);case'append':return pad+v('LIST')+'.append('+v('VALUE')+')\n';case'update':return pad+v('RECORD')+'['+quote(f.KEY)+'] = '+v('VALUE')+'\n';case'call':if(!functions.has(f.NAME))throw Error('Define this recipe before exporting.');return pad+functions.get(f.NAME)+'()\n';default:throw Error('Unsupported instruction block.');}}).join('');};
return `# Made with Kids Code Block Lab\n# Change the inputs below to test a new idea.\n# Python and block values have some different type rules.\nimport json\nimport math\n\ndef show(value):\n    if value is None:\n        return "nothing"\n    if isinstance(value, bool):\n        return str(value).lower()\n    if isinstance(value, (list, dict)):\n        return json.dumps(value, ensure_ascii=False, separators=(",", ":"))\n    if isinstance(value, float) and value.is_integer():\n        return str(int(value))\n    return str(value)\n\ndef value_type(value):\n    if value is None:\n        return "nothing"\n    if isinstance(value, bool):\n        return "boolean"\n    if isinstance(value, (int, float)):\n        return "number"\n    if isinstance(value, str):\n        return "text"\n    return "list" if isinstance(value, list) else "record"\n\nvariables = {}\ninputs = ${literal(inputs)}\n\n`+Object.entries(program.functions).map(([name,body])=>'# Recipe: '+String(name).replace(/[\r\n]/g,' ')+'\ndef '+functions.get(name)+'():\n'+lines(body,1)+'\n').join('')+lines(program.body);
}
